### ISSUE TITLE
‘gdImageGrayScale’ was not declared in this scope

### ISSUE THREAD

**Issue by d1april** [mikesmullin/node-gd#20]
The pull request  #16 with commit dc1e3cf5060e92d00983b9f3741908960686dfbb breaks node-gd on Debian 7.6.0 

It is not compatible with the headers from libgd2-xpm-dev
https://packages.debian.org/wheezy/libgd2-xpm-dev

The gdImageGrayScale function does not exist.

Current solution: Installing the previous commit.
npm -g install https://github.com/mikesmullin/node-gd/archive/c531d6a90d5c78abf658d7f21499e0be0fa5261c.tar.gz

The errors:
> make: Entering directory `/usr/local/lib/node_modules/node-gd/build'
>   CXX(target) Release/obj.target/node_gd/cpp/node-gd.o
> ../cpp/node-gd.cpp: In static member function ‘static v8::Handle<v8::Value> Gd::Image::StringFTBBox(const v8::Arguments&)’:
> ../cpp/node-gd.cpp:1051:7: warning: variable ‘color’ set but not used [-Wunused-but-set-variable]
> ../cpp/node-gd.cpp: In static member function ‘static v8::Handle<v8::Value> Gd::Image::GrayScale(const v8::Arguments&)’:
> ../cpp/node-gd.cpp:1322:27: error: ‘gdImageGrayScale’ was not declared in this scope
> make: *** [Release/obj.target/node_gd/cpp/node-gd.o] Error 1
> make: Leaving directory `/usr/local/lib/node_modules/node-gd/build'

**Comment by y-a-v-a** [comment]
Latest node-gd requires libgd2 version 2.1.x.
