### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by rsweeten** [mikesmullin/node-gd#22]
Hello,

I started getting a node-gyp rebuild error on mac OSX. Is there something obvious I'm missing? I have gd.. I also have command line tools installed (v. 2339)

Ray

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /path/to/my/dir/node_modules/node-gd
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE

npm ERR! node-gd@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-gd@0.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-gd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-gd
npm ERR! There is likely additional logging output above.

**Comment by y-a-v-a** [comment]
Hi, have you installed node through MacPorts? Then see https://github.com/mikesmullin/node-gd/blob/stable/binding.gyp for additional paths.

**Comment by throrin19** [comment]
I've the same error in node 0.12.2 installed with Ububntu Node source package.

**Comment by y-a-v-a** [comment]
The cpp code is written for node < 0.10.x (at least, for v8 version 3.1.1 or so) and since node 0.12.x they've done, as far as I know, an upgrade of v8 to something like 3.26.x. This requires a complete different writing of cpp extensions to node. Luckily, NAN is there.
See my other comment at issue 23 https://github.com/mikesmullin/node-gd/issues/23#issuecomment-100625631

**Comment by y-a-v-a** [comment]
The node-gd versions v0.2.x only build with nodejs v0.10.x and not with v0.12.x. Beside, you'll need to have libgd2 v2.1.x.
The new version, node-gd v0.3.x will build with nodejs v0.12.x, but of course, still only with libgd2 v2.1.x.
